### PR TITLE
Adopt cfep 25

### PR DESCRIPTION
**Pull request by soapy1**
ref: https://github.com/conda-forge/cfep/blob/main/cfep-25.md

This pr:
* creates a new build for conda-store 2024.10.1
* updates the min python version to 3.10

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by soapy1** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
Hm, why is this expanding the CI matrix to so many Python-specific jobs? It's still noarch:python after all 🤔 Could this be a `conda-smithy` bug @beckermr?

**Comment by peytondmurray** [comment]
Looks like 3.9 is still being built.

**Comment by soapy1** [comment]
oh, I think that was my fault for rewriting some git history and force pushing rapidly :O lemme trigger one more build and I think things should clear up :crossed_fingers:

**Comment by soapy1** [comment]
@conda-forge-admin, please rerender

**Comment by soapy1** [comment]
@conda-forge-admin, please rerender

**Comment by soapy1** [comment]
ok so, I think this might be a bug with conda-smithy.  When I test out re-rendering locally after modifying the recipe to not be a split package things work as expected. For example, 

just build one of the packages (not as a split package)
```
{% set name = "conda-store" %}
{% set version = "2024.10.1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/c/conda-store/conda_store-{{ version }}.tar.gz
    sha256: 2b2c5039776d299f14af48739701def9bfc3764f67f1b7335ae9f9d88cc52fc0
    folder: conda-store
  - url: https://pypi.org/packages/source/c/conda-store-server/conda_store_server-{{ version }}.tar.gz
    sha256: 61451e3893e8a109d7015dbedc4748691f59c11357f92ab2face5c0e66eef760
    folder: conda-store-server

build:
  number: 1
  noarch: python
  script: python -m pip install ./conda-store-server -vv --no-deps --no-build-isolation --no-index
  entry_points:
      - conda-store-server = conda_store_server._internal.server.__main__:main
      - conda-store-worker = conda_store_server._internal.worker.__main__:main
  requirements:
    host:
      - python {{ python_min }}
      - pip
      - hatchling >=1.14.0
      - hatch-vcs
    run:
      - alembic
      - celery
      - conda
      - conda-docker  # [linux]
      - __linux  # [linux]
      - __osx    # [osx]
      - __win    # [win]
      - conda-pack
      - conda-lock
      - constructor
      - fastapi
      - filelock
      - itsdangerous
      - jinja2
      - minio
      - pydantic <2.0a0
      - pyjwt
      - python >={{ python_min }}
      - python-docker
      - python-multipart
      - pyyaml
      - redis-py
      - requests
      - sqlalchemy <2.0a0
      - traitlets
      - uvicorn
      - yarl
      - psycopg2
      - pymysql
    run_constrained:
      - {{ pin_subpackage('conda-store', min_pin='x.x.x', max_pin='x.x.x') }}

  test:
    imports:
      - conda_store_server
    commands:
      - conda-store-server --help
      - conda-store-worker --help

about:
  home: https://github.com/conda-incubator/conda-store
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Conda Environment Management, Builds, and Serve
  description: |
    End users think in terms of environments not packages. The core
    philosophy of conda-store is to serve identical conda environments
    in as many ways as possible. Conda Store controls the environment
    lifecycle: management, builds, and serving of environments.
  doc_url: https://conda.store/
  dev_url: https://github.com/conda-incubator/conda-store

extra:
  feedstock-name: conda-store
  recipe-maintainers:
    - peytondmurray
    - soapy1
    - trallard
    - jaimergp
```

run the rerender

```
$ conda-smithy rerender
. . .
INFO:conda_smithy.configure_feedstock:You can commit the changes with:

    git commit -m "MNT: Re-rendered with conda-build 24.9.0, conda-smithy 3.44.3, and conda-forge-pinning 2024.11.12.14.24.54"
```

the generated `.ci_support/linux_64.yaml` looks correct
```
cdt_name:
- conda
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
python:
- 3.12.* *_cpython
python_min:
- '3.10'
```

**Comment by beckermr** [comment]
Try using jinja2 to set python_min to 3.10 instead of the conda build config.

**Comment by soapy1** [comment]
Ah I see, gotcha! Thanks for taking a look :eyes:

**Comment by soapy1** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
Hrmmm that didn't work. I'll take a closer look tomorrow.

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
So as far as I can tell, this regex for finding variants is wrong:

https://github.com/conda/conda-build/blob/main/conda_build/variants.py#L752

For `python`, it renders to `\{\s*(?:pin_[a-z]+\(\s*?['\"])?python[^'\"]*?\}\}`. This matches both `{{ python }}` and `{{ python_min }}` when it should only match `{{ python }}`. I would have hoped a unittest in conda-build would have caught this, but here we are. :/

**Comment by beckermr** [comment]
This PR appears to have broken matches to pin_compatible statements: https://github.com/conda/conda-build/pull/2838

**Comment by beckermr** [comment]
This PR appears to fix things: https://github.com/conda/conda-build/pull/5535

**Comment by soapy1** [comment]
wow @beckermr thanks for looking into this!

**Review by trallard — APPROVED** [review]
Thank you a bunch @soapy1 and @beckermr ✨ will approve and merge right aware 🚀

**Pull request merged**
